# Generated by Django 6.0.3 on 2026-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfappraisalsubmission',
            old_name='admin_remarks',
            new_name='admin_remark',
        ),
        migrations.AlterField(
            model_name='selfappraisalsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
